# Generated by Django 4.0 on 2024-04-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t01div10',
            options={'verbose_name': 'division'},
        ),
        migrations.AlterModelTable(
            name='t01div10',
            table='T01Div10',
        ),
    ]
